# Generated by Django 3.2 on 2021-08-19 15:04

import adminpanelapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Shipping User's Full Name")),
                ('phone', models.CharField(max_length=20, verbose_name="Shipping User's Phone Number")),
                ('address', models.CharField(help_text='(House No., Flat No., Road Name/No., Village/Area, Thana, Post Office)', max_length=500, verbose_name='Full Address')),
                ('post_code', models.CharField(max_length=20, verbose_name='Post Code')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_shipping_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Addresses',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default=adminpanelapp.models.default_profile_image, upload_to=adminpanelapp.models.get_profile_images_filepath, verbose_name='Profile Picture')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone_one', models.CharField(max_length=20)),
                ('phone_two', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Billing User's Full Name")),
                ('phone', models.CharField(max_length=20, verbose_name="Billing User's Phone Number")),
                ('address', models.CharField(help_text='(House No., Flat No., Road Name/No., Village/Area, Thana, Post Office)', max_length=500, verbose_name='Full Address')),
                ('post_code', models.CharField(max_length=20, verbose_name='Post Code')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_billing_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
    ]
