# Generated by Django 3.2 on 2021-08-19 15:06

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import ecomapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('company_logo', django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Size Recommended: 256x256', keep_meta=True, quality=100, size=[256, 256], upload_to=ecomapp.models.image_directory)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=45)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ecomapp.category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
            },
        ),
    ]
