# Generated by Django 3.2 on 2021-08-19 15:06

from django.db import migrations, models
import django.db.models.deletion
import productapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=264, verbose_name='Product Name')),
                ('product_quantity', models.IntegerField(verbose_name='Quantity')),
                ('product_price', models.IntegerField(verbose_name='Price')),
                ('product_discount', models.IntegerField(help_text='%', verbose_name='Discount')),
                ('product_new_price', models.IntegerField(blank=True, help_text='Warning: Do not edit this field!!!', verbose_name='New Price')),
                ('product_description', models.TextField(verbose_name='Description')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='ecomapp.category')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_company', to='ecomapp.company')),
                ('product_colors', models.ManyToManyField(to='productapp.Colors', verbose_name='Available Colors')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to=productapp.models.image_dir, verbose_name='Product Images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_product', to='productapp.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_sizes',
            field=models.ManyToManyField(to='productapp.Sizes', verbose_name='Available Sizes'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='ecomapp.subcategory'),
        ),
    ]
