# Generated by Django 3.2.6 on 2021-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_colors',
            field=models.ManyToManyField(blank=True, to='productapp.Colors', verbose_name='Available Colors'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sizes',
            field=models.ManyToManyField(blank=True, to='productapp.Sizes', verbose_name='Available Sizes'),
        ),
    ]
