# Generated by Django 3.2.6 on 2021-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.IntegerField(blank=True, help_text='Do not Edit!', null=True, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.IntegerField(blank=True, help_text='Do not Edit!', null=True, verbose_name='Total Rating'),
        ),
    ]
