# Generated by Django 3.2.6 on 2021-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_product_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=15, verbose_name='Coupon Code')),
                ('discount_amount', models.IntegerField(verbose_name='Discounted Amount')),
                ('is_active', models.BooleanField(verbose_name='Activate Coupon')),
            ],
        ),
    ]
