# Generated by Django 3.2.6 on 2021-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
