# Generated by Django 3.2.6 on 2021-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Coupon Code'),
        ),
    ]
