# Generated by Django 3.2.6 on 2021-09-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_alter_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='count',
        ),
    ]
