# Generated by Django 3.2.6 on 2021-09-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_remove_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
