# Generated by Django 3.2.6 on 2021-09-12 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0010_alter_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
