# Generated by Django 3.2.6 on 2021-09-13 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0012_alter_product_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
